name             	'pricetool'
maintainer       	'My Company'
maintainer_email 	'my-email@email.com'
license          	'All rights reserved'
description      	'Installs/Configures pricetool'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          	'0.1.0'

depends 					'git'
depends						'apt'
depends 					'chef-client'
depends						'rbenv'
depends						'redisio'
depends						'mysql'
depends						'database'
depends						'application_ruby'
